// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AspectRatio } from "./AspectRatio";
import type { Resolution } from "./Resolution";
import type { SearchParametersCategories } from "./SearchParametersCategories";
import type { SearchParametersColor } from "./SearchParametersColor";
import type { SearchParametersOrder } from "./SearchParametersOrder";
import type { SearchParametersPurities } from "./SearchParametersPurities";
import type { SearchParametersSort } from "./SearchParametersSort";
import type { SearchParametersTopRange } from "./SearchParametersTopRange";

export type SearchParameters = { q: string | null, categories: SearchParametersCategories | null, purity: SearchParametersPurities | null, sorting: SearchParametersSort, order: SearchParametersOrder, topRange: SearchParametersTopRange, atleast: Resolution | null, resolutions: Array<Resolution> | null, ratios: Array<AspectRatio> | null, colors: Array<SearchParametersColor> | null, page: bigint | null, seed: string | null, };
