// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Collection = { id: number, label: string, views: number, public: number, count: number, };
