// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Query } from "./Query";

export type Meta = { current_page: number, last_page: number, per_page: number, total: number, query: Query | null, seed: string | null, };
